options:  
  logging: CLOUD_LOGGING_ONLY  

steps:  
  # Step 0: Build Docker image  
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thriftly-backend', '-f', 'thriftly-backend/Dockerfile', 'thriftly-backend']  

  # Step 1: Push Docker image to Google Container Registry  
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['push', 'gcr.io/$PROJECT_ID/thriftly-backend']  

  # Step 2: Deploy to Google Cloud Run  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  
    entrypoint: gcloud  
    args:  
      - 'run'  
      - 'deploy'  
      - 'thriftly-backend'  
      - '--image'  
      - 'gcr.io/$PROJECT_ID/thriftly-backend'  
      - '--platform'  
      - 'managed'  
      - '--region'  
      - 'us-central1'  
      - '--allow-unauthenticated'  
      - '--set-env-vars'  
      - 'DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME}'  

images:  
  - 'gcr.io/$PROJECT_ID/thriftly-backend'  
