options:  
  logging: CLOUD_LOGGING_ONLY  

steps:  
  # Build  
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thriftly-ml', '.']  
    dir: 'ML/models'      
  # Push  
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['push', 'gcr.io/$PROJECT_ID/thriftly-ml']  

  # Deploy  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  
    entrypoint: gcloud  
    args:  
      - 'run'  
      - 'deploy'  
      - 'thriftly-ml'  
      - '--image'  
      - 'gcr.io/$PROJECT_ID/thriftly-ml'  
      - '--platform'  
      - 'managed'  
      - '--region'  
      - 'asia-southeast2'  
      - '--allow-unauthenticated'  
      - '--memory'  
      - '2Gi'  
      - '--cpu'  
      - '2'  
      - '--set-env-vars'  
      - 'DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME}'  

substitutions:  
  _DB_HOST: '34.101.195.146'  
  _DB_USER: 'root'  
  _DB_NAME: 'thriftly-mysql-db'  
  _DB_PASSWORD: 'kimochi:)-!@#'  

images:  
  - 'gcr.io/$PROJECT_ID/thriftly-ml'  
